version: "3"
services:
  mongo:
    container_name: kohbot-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_DB: kohbot
      MONGO_INITDB_ROOT_USERNAME: kohbot
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
    volumes: 
      - ./mongo-volume:/data/db

  mongo-express:
    container_name: kohbot-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kohbot
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpassword

  # api:
  #   container_name: kohbot-api
  #   build: .
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 4000:4000
  #   environment:
  #     - MONGO_URL=mongodb://kohbot:supersecretpassword@mongo:27017
  #     - PORT=4000
